import './globals.scss'
import {Inter} from 'next/font/google'
import {TheHeader} from "@/components/TheHeader";
import {Metadata} from "next";
import {Providers} from "@/components/Providers";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Home | Next test',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
            <TheHeader/>
            <main>
              {children}
            </main>
        </Providers>
      </body>
    </html>
  )
}
